from django import forms  
from .models import MigrationTrackerModel  
class MigrationTrackingForm(forms.ModelForm):  
    class Meta:  
        model = MigrationTrackerModel  
        fields =   ['app_id',
                    'app_name', 
                    'pdo',
                    'existing_platform', 
                    'sla', 
                    'cia',
                    'll4', 
                    'll5',
                    'll6', 
                    'pdo_contacts',                     
                    'app_arch_contacts', 
                    'planned_launch_date',
                    'quater_of_launch', 
                    'planned_decom_date', 
                    'assigned_wavelead',
                    'assigned_dl_il',
                    'assigned_team', 
                    'assigned_techlead', 
                    'assigned_ce', 
                    'assessment_status', 
                    'fsa_status',
                    'costestimation_status',
                    'fsa_link',
                    'costestimation_link',
                    'status_update',
                    'servicemapping_updated',
                    'costestimation_updated',
                    'migration_scope',
                    'migration_category',
                    'architecture_finalized',
                    'onboarding_dev',
                    'onboarding_qa',
                    'onboarding_prod',
                    'code_changes',
                    'uat',
                    'devsecops',
                    'remarks'                    
                    ] 
        widgets = { 'app_id': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'app_name': forms.NumberInput(attrs={ 'class': 'form-control' }), 
                    'pdo': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'existing_platform': forms.NumberInput(attrs={ 'class': 'form-control' }), 
                    'sla': forms.NumberInput(attrs={ 'class': 'form-control' }), 
                    'cia': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'll4': forms.NumberInput(attrs={ 'class': 'form-control' }), 
                    'll5': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'll6': forms.NumberInput(attrs={ 'class': 'form-control' }), 
                    'pdo_contacts': forms.NumberInput(attrs={ 'class': 'form-control' }),                     
                    'app_arch_contacts': forms.NumberInput(attrs={ 'class': 'form-control' }), 
                    'planned_launch_date': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'quater_of_launch': forms.NumberInput(attrs={ 'class': 'form-control' }), 
                    'planned_decom_date': forms.NumberInput(attrs={ 'class': 'form-control' }), 
                    'assigned_wavelead': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'assigned_dl_il': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'assigned_team': forms.NumberInput(attrs={ 'class': 'form-control' }), 
                    'assigned_techlead': forms.NumberInput(attrs={ 'class': 'form-control' }), 
                    'assigned_ce': forms.NumberInput(attrs={ 'class': 'form-control' }), 
                    'assessment_status': forms.NumberInput(attrs={ 'class': 'form-control' }), 
                    'fsa_status': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'costestimation_status': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'fsa_link': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'costestimation_link': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'status_update': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'servicemapping_updated': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'costestimation_updated': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'migration_scope': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'migration_category': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'architecture_finalized': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'onboarding_dev': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'onboarding_qa': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'onboarding_prod': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'code_changes': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'uat': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'devsecops': forms.NumberInput(attrs={ 'class': 'form-control' }),
                    'remarks': forms.NumberInput(attrs={ 'class': 'form-control' }),                
                    }