# Generated by Django 5.0.3 on 2024-03-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicemapping_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('app_name', models.CharField(max_length=100)),
                ('pdo', models.CharField(max_length=100)),
                ('sla', models.CharField(max_length=100)),
                ('current_state_tech_stack', models.CharField(max_length=100)),
                ('current_state_db', models.CharField(max_length=100)),
                ('future_state_tech_stack', models.CharField(max_length=100)),
                ('migration_roadmap', models.CharField(max_length=100)),
                ('in_scope', models.CharField(max_length=100)),
                ('architecture_type', models.CharField(max_length=100)),
                ('cloud_run', models.CharField(max_length=100)),
                ('gcp_caas', models.CharField(max_length=100)),
                ('onprem_caas', models.CharField(max_length=100)),
                ('external_load_balancer', models.CharField(max_length=100)),
                ('internal_load_balancer', models.CharField(max_length=100)),
                ('apigee', models.CharField(max_length=100)),
                ('cloud_armor', models.CharField(max_length=100)),
                ('cloud_dns', models.CharField(max_length=100)),
                ('compute_engine', models.CharField(max_length=100)),
                ('cloud_function', models.CharField(max_length=100)),
                ('cloud_storage', models.CharField(max_length=100)),
                ('cloudsql_mssql_se', models.CharField(max_length=100)),
                ('cloudsql_mssql_ee', models.CharField(max_length=100)),
                ('cloudsql_pg', models.CharField(max_length=100)),
                ('onprem_db', models.CharField(max_length=100)),
                ('big_query', models.CharField(max_length=100)),
                ('cloud_scheduler', models.CharField(max_length=100)),
                ('memory_store', models.CharField(max_length=100)),
                ('cloud_monitoring', models.CharField(max_length=100)),
                ('cloud_logging', models.CharField(max_length=100)),
                ('secret_manager', models.CharField(max_length=100)),
                ('fire_store', models.CharField(max_length=100)),
                ('mongo_db', models.CharField(max_length=100)),
                ('cloud_build', models.CharField(max_length=100)),
                ('adfs', models.CharField(max_length=100)),
                ('azure_ad', models.CharField(max_length=100)),
                ('deployment_topology', models.CharField(max_length=100)),
                ('iac_pipeline', models.CharField(max_length=100)),
                ('app_pipeline', models.CharField(max_length=100)),
                ('fossa', models.CharField(max_length=100)),
                ('checkmarx', models.CharField(max_length=100)),
                ('sonarqube', models.CharField(max_length=100)),
                ('cycode', models.CharField(max_length=100)),
                ('crunch_42', models.CharField(max_length=100)),
                ('automated_testing', models.CharField(max_length=100)),
                ('sre', models.CharField(max_length=100)),
                ('migration_scope', models.CharField(max_length=100)),
                ('migration_category', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'servicemapping_table',
            },
        ),
    ]
