# Generated by Django 5.0.3 on 2024-03-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcpservicemappings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicemapping_model',
            new_name='ServiceMappingModel',
        ),
    ]
