# Generated by Django 5.0.3 on 2024-03-09 01:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcpservicemappings', '0002_rename_servicemapping_model_servicemappingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemappingmodel',
            name='cia',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
