# Generated by Django 5.0.3 on 2024-03-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcpservicemappings', '0004_servicemappingmodel_automated_testing_after_deploy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemappingmodel',
            name='automated_testing',
        ),
        migrations.RemoveField(
            model_name='servicemappingmodel',
            name='mongo_db',
        ),
    ]
