# Generated by Django 5.0.3 on 2024-03-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcpservicemappings', '0005_remove_servicemappingmodel_automated_testing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemappingmodel',
            name='app_id',
            field=models.CharField(max_length=100),
        ),
    ]
